import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from core.language_layer import get, check_language_mismatch


class TestLanguageLayer:
    def test_get_find_uk(self):
        assert get("find", "uk") == "Знайди"

    def test_get_find_ru(self):
        assert get("find", "ru") == "Найди"

    def test_get_find_en(self):
        assert get("find", "en") == "Find"

    def test_get_count_uk(self):
        assert get("count", "uk") == "Порахуй"

    def test_get_count_ru(self):
        assert get("count", "ru") == "Посчитай"

    def test_get_count_en(self):
        assert get("count", "en") == "Count"

    def test_get_color_uk(self):
        assert get("color", "uk") == "Розфарбуй"

    def test_get_color_ru(self):
        assert get("color", "ru") == "Раскрась"

    def test_check_language_mismatch_uk_clean(self):
        issues = check_language_mismatch("Знайди фігуру. Порахуй зірки.", "uk")
        # 'найди' is substring of 'знайди' but not a standalone word
        assert len(issues) == 0, f"Clean UK text flagged: {issues}"

    def test_check_language_mismatch_uk_with_ru(self):
        issues = check_language_mismatch("Найди ответ", "uk")
        assert len(issues) > 0, "RU word in UK text not detected"

    def test_check_language_mismatch_ru_clean(self):
        issues = check_language_mismatch("Найди ответ. Посчитай звезды.", "ru")
        assert len(issues) == 0

    def test_check_language_mismatch_ru_with_uk(self):
        issues = check_language_mismatch("Знайди відповідь", "ru")
        assert len(issues) > 0, "UK word in RU text not detected"

    def test_check_tech_words_clean(self):
        from core.language_layer import check_tech_words
        issues = check_tech_words("Математика для детей")
        assert len(issues) == 0

    def test_check_tech_words_detected(self):
        from core.language_layer import check_tech_words
        issues = check_tech_words("generated by ai")
        assert len(issues) > 0
